# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'timeToRead' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'
  # Pods for timeToRead

  target 'timeToReadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'timeToReadUITests' do
    # Pods for testing
  end

end
